title: Spring Boot Tutorials
email: your-email@example.com
description: Spring Boot Tutorials. Hands-on examples. - Basics of Spring Boot. Covers Spring Boot Starter Projects, Spring Initializr, Creating REST Services, Unit and Integration tests, Profiles, Spring Boot Data JPA, Actuator and Security
url: 'https://www.springboottutorial.com'
twitter_username: in28Minutes
github_username: in28Minutes
linkedin_username: rangakaranam
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Google services
google_verification:
# Use either direct GA implementation or set up GTM account
# - using both will skew your data (leave blank to not use at all)
google_analytics: UA-32942307-5
google_tag_manager:
# Bing services
bing_verification:
# Facebook Page integration
# (for instant articles and other stuff)
fb_page: false
fb_page_id:
# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10
